In [31]:
import numpy as np
from jplephem.spk import SPK
import time

In [25]:
kernel = SPK.open('de405.bsp')

In [26]:
print(kernel)

File type NAIF/DAF and format BIG-IEEE with 15 segments:
2433282.50..2469807.50  Solar System Barycenter (0) -> Mercury Barycenter (1)
2433282.50..2469807.50  Solar System Barycenter (0) -> Venus Barycenter (2)
2433282.50..2469807.50  Solar System Barycenter (0) -> Earth Barycenter (3)
2433282.50..2469807.50  Solar System Barycenter (0) -> Mars Barycenter (4)
2433282.50..2469807.50  Solar System Barycenter (0) -> Jupiter Barycenter (5)
2433282.50..2469807.50  Solar System Barycenter (0) -> Saturn Barycenter (6)
2433282.50..2469807.50  Solar System Barycenter (0) -> Uranus Barycenter (7)
2433282.50..2469807.50  Solar System Barycenter (0) -> Neptune Barycenter (8)
2433282.50..2469807.50  Solar System Barycenter (0) -> Pluto Barycenter (9)
2433282.50..2469807.50  Solar System Barycenter (0) -> Sun (10)
2433282.50..2469807.50  Earth Barycenter (3) -> Moon (301)
2433282.50..2469807.50  Earth Barycenter (3) -> Earth (399)
2433282.50..2469807.50  Mercury Barycenter (1) -> Mercury (199)
24332

In [63]:
kernel[0,3].compute(2433282.50)

array([-2.72009141e+07,  1.32944597e+08,  5.76436519e+07])

In [28]:
2451545 + 12*365.25 + 3*31 + 29 + 30 + 6

2456086.0

In [105]:
time_start = time.time()
for delta_date in range(36525*4):
    date = 2469807.50 - 1 - delta_date*0.25
    v = kernel[0,2].compute(date) + kernel[2,299].compute(date)
    e = kernel[0,3].compute(date) + kernel[3,399].compute(date)
    s = kernel[0,10].compute(date)
    A = v - e ;B = s - e;
    cos = A.dot(B)/(np.sqrt(A.dot(A))*np.sqrt(B.dot(B)))
#     delta = 1 - cos
    if cos > 0.9999891932763468:
        if np.sqrt(A.dot(A)) < np.sqrt(B.dot(B)):
            print('yeah!',date,cos)
            print(v,e,s)

print(time.time() - time_start)

yeah! 2456084.5 0.999995003344639
[-27568119.0403795  -96794233.50528169 -41827730.92094239] [-3.83103060e+07 -1.35124650e+08 -5.85817432e+07] [-372410.19946035 -266981.93919819 -118409.64125584]
yeah! 2453164.75 0.9999919834249656
[-22628500.0810582  -97561869.43276632 -42433089.31343979] [-3.16868171e+07 -1.36376126e+08 -5.91376224e+07] [ 593197.49337586 -237282.02834439 -116354.39324538]
38.60043168067932


In [107]:
(2433282.50 - 2451545)/365.5

-49.965800273597814

In [92]:
np.cos(np.arctan((6.955E5)/(1.496E8)))

0.9999891932763468

In [70]:
segment = kernel[3,399]
segment.start_jd

2433282.500476666

In [100]:
a = np.array([1.1,2,3])
b = np.array([-3,-2.3,-1])
a.dot(b)

-10.9