 Draft paper for testing some syntax

In [2]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
import datetime
import time

from scipy import interpolate 

from DDS_Laplace import *

import DDS_CMpack as DDS

%matplotlib inline

## 最小二乘法的测试

In [3]:
A = np.array([[1,2,3,5,6,7],[40,50,60,20,40,60],[7,8,9,10,11,13]])
b = np.array([1,3,5])

A

array([[ 1,  2,  3,  5,  6,  7],
       [40, 50, 60, 20, 40, 60],
       [ 7,  8,  9, 10, 11, 13]])

In [4]:
AA = np.array(A)
b = np.array(b)

print(AA.shape,b.shape)

ans = np.linalg.solve(np.dot(AA.T.copy(),AA),\
                         np.dot(AA.T.copy(),b))

r0_a = [ans[0]**2 , ans[1]**2 , ans[2]**2]
v0_a = [ans[3]**2 , ans[4]**2 , ans[5]**2]

r0 = np.sqrt(ans[0]**2 + ans[1]**2 + ans[2]**2)
v0 = np.sqrt(ans[3]**2 + ans[4]**2 + ans[5]**2)
# print(Nwind,':',r0,v0)

(3, 6) (3,)


In [5]:
r0_a

[0.0015088471635015656, 35.95743454844715, 56.05649385867651]

In [6]:
v0_a

[14.462633845633679, 3.2046973451172898, 6.452390631416223]

In [7]:
AA.T*AA

ValueError: operands could not be broadcast together with shapes (6,3) (3,6) 

In [8]:
?np.linalg.lstsq

In [27]:
c= np.array([[1,2,3],[40,50,60],[700,100,900]])
c

array([[  1,   2,   3],
       [ 40,  50,  60],
       [700, 100, 900]])

In [28]:
c.T.dot(c)

array([[491601,  72002, 632403],
       [ 72002,  12504,  93006],
       [632403,  93006, 813609]])

In [29]:
d = np.array([4,9,100])
d

array([  4,   9, 100])

In [30]:
c.T.dot(d)

array([70364, 10458, 90552])

In [31]:
ans = np.linalg.solve(np.dot(c.T.copy(),c),\
                         np.dot(c.T.copy(),d))
ans

array([-3.32142857, -0.45714286,  2.7452381 ])

In [34]:
ans = np.linalg.solve(c,d)
ans

array([-3.32142857, -0.45714286,  2.7452381 ])

In [32]:
ans = np.linalg.lstsq(c,d)

/Users/dengdingshan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [33]:
ans[0]

array([-3.32142857, -0.45714286,  2.7452381 ])