计算地球极点的移动

等价于

计算春分点的移动

In [2]:
import numpy as np
from jplephem import Ephemeris
import datetime
import ltpecl
import ltpequ

In [4]:
print(ltpecl.__doc__)
print(ltpequ.__doc__)

This module 'ltpecl' is auto-generated with f2py (version:2).
Functions:
  vec = iau_ltpecl(epj)
.
This module 'ltpequ' is auto-generated with f2py (version:2).
Functions:
  veq = iau_ltpequ(epj)
.


In [5]:
year_begin = -300
year_end = 2018
vec300BC = ltpecl.iau_ltpecl(year_begin)
veq300BC = ltpequ.iau_ltpequ(year_begin)
vec2018AD = ltpecl.iau_ltpecl(year_end)
veq2018AD = ltpequ.iau_ltpequ(year_end)

cross300BC = np.cross(veq300BC,vec300BC)
cross2018AD = np.cross(veq2018AD,vec2018AD)

In [6]:
def Rx(x):
    import numpy as np
    # x is in the unit of deg, while xx is in the unit of rad
    xx = x*2*np.pi/360
    Rx = np.array([[1,0,0],\
                     [0,np.cos(xx),np.sin(xx)],\
                     [0,-np.sin(xx),np.cos(xx)]])
    return Rx

def equator2ecliptic(origin,epsilon,key):
    # epsilon是黄赤交角
    # from equ to ecl , key = 1
    # from ec1 to equ , key = 2
    # origin是个np.的1x3向量
    if key == 1:
        output = np.dot(origin,Rx(epsilon).T)
    elif key == 2:
        output = np.dot(origin,Rx(-epsilon).T)
    else:
        print('you need to input a key as: \n from equ to ecl , key = 1' + \
        '\n from ec1 to equ , key = 2')

    return output

In [16]:
epsilon = 84381.488/60/60
print(epsilon)

ecl300BC = equator2ecliptic(cross300BC,epsilon,1)
ecl2018AD = equator2ecliptic(cross2018AD,epsilon,1)

ecl300BC,ecl2018AD

23.439302222222224


(array([0.34141822, 0.21307526, 0.0011194 ]),
 array([ 3.97735638e-01, -1.74552426e-03, -1.39759533e-06]))

In [14]:
ecl_300 = ecl300BC[0:2]
ecl2018 = ecl2018AD[0:2]

array([ 0.39773564, -0.00174552])

In [15]:
cos = np.dot(ecl_300,ecl2018)/(np.sqrt(np.dot(ecl_300,ecl_300)) * np.sqrt(np.dot(ecl2018,ecl2018)))
np.degrees(np.arccos(cos)),'degree'

(32.219270876838216, 'degree')